// Code generated by hand for a fixture. DO NOT EDIT.

package x

// Gen sits in a generated file.
func Gen() int { return 7 }

// GT sits in a generated file.
type GT struct{}

// GM sits in a generated file.
func (GT) GM() int { return 8 }
