package source

import (
	"go/build"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"testing"
)

func fixture(t *testing.T) Module {
	t.Helper()
	m, err := FindModule(filepath.Join("testdata", "mod", "internal", "inner"))
	if err != nil {
		t.Fatal(err)
	}
	return m
}

func TestFindModuleWalksUpAndReadsAQuotedPath(t *testing.T) {
	m := fixture(t)
	if m.Path != "example.com/mod" {
		t.Errorf("Path = %q, want example.com/mod", m.Path)
	}
	want, _ := filepath.Abs(filepath.Join("testdata", "mod"))
	if m.Root != want {
		t.Errorf("Root = %q, want %q", m.Root, want)
	}
}

func TestFindModuleFailsWithoutGoMod(t *testing.T) {
	if _, err := FindModule(t.TempDir()); err == nil {
		t.Fatal("FindModule found a module in an empty temp directory")
	}
}

func TestPackagesSkipsWhatTheGoCommandSkips(t *testing.T) {
	pkgs, err := Packages(fixture(t), Config{})
	if err != nil {
		t.Fatal(err)
	}
	var dirs []string
	for _, p := range pkgs {
		dirs = append(dirs, p.Dir)
	}
	want := []string{".", "internal/inner", "onlytests", "sub/deeper"}
	if !reflect.DeepEqual(dirs, want) {
		t.Errorf("dirs = %q, want %q", dirs, want)
	}
}

func TestPackagesNamesFilesFromTheModuleRoot(t *testing.T) {
	pkgs, err := Packages(fixture(t), Config{})
	if err != nil {
		t.Fatal(err)
	}
	root, inner, only := pkgs[0], pkgs[1], pkgs[2]
	if root.ImportPath != "example.com/mod" || root.Name != "mod" {
		t.Errorf("root = %q %q", root.ImportPath, root.Name)
	}
	if inner.ImportPath != "example.com/mod/internal/inner" || inner.Name != "inner" {
		t.Errorf("inner = %q %q", inner.ImportPath, inner.Name)
	}
	if !reflect.DeepEqual(inner.GoFiles, []string{"internal/inner/inner.go"}) {
		t.Errorf("inner.GoFiles = %q", inner.GoFiles)
	}
	if len(only.GoFiles) != 0 || !reflect.DeepEqual(only.TestFiles, []string{"onlytests/x_test.go"}) {
		t.Errorf("onlytests = %q %q", only.GoFiles, only.TestFiles)
	}
	if only.Name != "onlytests" {
		t.Errorf("onlytests.Name = %q", only.Name)
	}
}

func TestPackagesHonorsBuildTagsAndLeavesGeneratedAndCgoFilesImmutable(t *testing.T) {
	m := fixture(t)
	plain, err := Packages(m, Config{})
	if err != nil {
		t.Fatal(err)
	}
	tagged, err := Packages(m, Config{Tags: []string{"flinchfixture"}})
	if err != nil {
		t.Fatal(err)
	}
	cgo := []string{}
	if build.Default.CgoEnabled {
		cgo = []string{"cgo.go"}
	}
	want := append(append([]string{"a.go", "b.go"}, cgo...), "gen.go")
	slices.Sort(want)
	if got := plain[0].GoFiles; !reflect.DeepEqual(got, want) {
		t.Errorf("GoFiles = %q, want %q", got, want)
	}
	if got := plain[0].Mutable; !reflect.DeepEqual(got, []string{"a.go", "b.go"}) {
		t.Errorf("Mutable = %q, want a.go and b.go", got)
	}
	if got := plain[0].TestFiles; !reflect.DeepEqual(got, []string{"a_test.go"}) {
		t.Errorf("TestFiles = %q", got)
	}
	if got := tagged[0].Mutable; !reflect.DeepEqual(got, []string{"a.go", "b.go", "tagged.go"}) {
		t.Errorf("tagged Mutable = %q", got)
	}
	if got := tagged[0].TestFiles; !reflect.DeepEqual(got, []string{"a_test.go", "tagged_test.go"}) {
		t.Errorf("tagged TestFiles = %q", got)
	}
}

func TestGeneratedNeedsTheMarkerBeforeThePackageClause(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "go.mod", "module example.com/g\n")
	write(t, dir, "late.go", "package g\n\n// Code generated by hand. DO NOT EDIT.\n")
	write(t, dir, "early.go", "// Code generated by hand. DO NOT EDIT.\n\npackage g\n")
	write(t, dir, "loose.go", "// Code generated by hand. DO NOT EDIT\n\npackage g\n")
	pkgs, err := Packages(Module{Root: dir, Path: "example.com/g"}, Config{})
	if err != nil {
		t.Fatal(err)
	}
	if got := pkgs[0].Mutable; !reflect.DeepEqual(got, []string{"late.go", "loose.go"}) {
		t.Errorf("Mutable = %q, want late.go and loose.go", got)
	}
}

func TestParseNamesUnitsAndTypes(t *testing.T) {
	m := fixture(t)
	pkgs, err := Packages(m, Config{})
	if err != nil {
		t.Fatal(err)
	}
	p, err := Parse(m, pkgs[0])
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(p.Names, pkgs[0].GoFiles) {
		t.Errorf("Names = %q, want %q", p.Names, pkgs[0].GoFiles)
	}
	if !reflect.DeepEqual(p.Types, []string{"S", "T", "U"}) {
		t.Errorf("Types = %q", p.Types)
	}
	var names []string
	for _, u := range p.Units {
		names = append(names, u.Name)
	}
	for _, want := range []string{"V", "A", "A.func1", "T.M", "T.N", "init.0", "init.1", "Generated"} {
		if !slices.Contains(names, want) {
			t.Errorf("units %q lack %s", names, want)
		}
	}
	if slices.Contains(names, "W") {
		t.Errorf("units %q hold W, which has no initializer", names)
	}
	if pos := p.Fset.Position(p.Files[0].Package); pos.Filename != "a.go" {
		t.Errorf("file set names a.go %q", pos.Filename)
	}
}

func write(t *testing.T, dir, name, text string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
}
